[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_BASE_PATH = "/.netlify/functions"

[functions]
  directory = "netlify/functions"

[functions."cron-sync"]
  schedule = "0 21 * * *"

[[plugins]]
  package = "@netlify/plugin-nextjs"