[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_PUBLIC_API_BASE_PATH = "/.netlify/functions"

[functions]
directory = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-nextjs"